### ISSUE TITLE
Add timestamps to the log embeds

### ISSUE THREAD

**Issue by netux** [LittleEndu/pxls-alert-bot#1]
Discord doesn't do a great job at separating every message and giving a different time or date to each one of them.
It would helpful to know the exact moment a pixel was placed (or the moment pxls-alert-bot received the placement). Also, [Discord already provides a way to add timestamps to a message)](https://discordapp.com/developers/docs/resources/channel#embed-object).

**Comment by LittleEndu** [comment]
Logs have been removed as they were rate limiting the bot (and I found no real solution around that). They give little to no extra info. You could just look at the canvas and see what has happened, knowing when it happened isn't going to help you at all.
